DROP TABLE IF EXISTS transacciones;
DROP TYPE IF EXISTS tipo_transaccion;
DROP TABLE IF EXISTS cuentas;
DROP TABLE IF EXISTS usuarios;

CREATE TABLE IF NOT EXISTS usuarios (
    id_usuario SERIAL PRIMARY KEY,
    usuario VARCHAR(255),
    nombre VARCHAR(255),
    email VARCHAR(255),
    clave VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS cuentas (
    id_cuenta SERIAL PRIMARY KEY,
    id_usuario BIGINT,
    numero_cuenta VARCHAR(255),
    tipo_cuenta VARCHAR(255) NOT NULL,
    saldo DECIMAL,
    limite_retiro_diario DECIMAL,
    FOREIGN KEY (id_usuario) REFERENCES usuarios(id_usuario)
);

CREATE TYPE tipo_transaccion AS ENUM ('DEPOSITO', 'RETIRO', 'TRANSFERENCIA');

CREATE TABLE IF NOT EXISTS transacciones (
    id_transaccion BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- otra manera de generar un id autoincrementable que no sea SERIAL
    id_cuenta BIGINT,
    tipo tipo_transaccion,  -- Utiliza el tipo de enum creado
    fecha_transaccion TIMESTAMP(6),
    monto DECIMAL
);